#!/usr/bin/env python3
"""Regenerate the checked-in standard capability definition table."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools" / "terminfo-metadata" / "standard-capabilities.tsv"
OUTPUT = ROOT / "src" / "Capabilities" / "StandardCapabilityDefinitions.Generated.cs"

EXPECTED_COUNTS = {
    "B": 44,
    "N": 39,
    "S": 414,
}
KIND_INFO = {
    "B": ("Boolean", "BooleanCapability", "Boolean"),
    "N": ("Numeric", "NumericCapability", "Number"),
    "S": ("String", "StringCapability", "String"),
}
ENUM_FILES = {
    "B": ROOT / "src" / "Capabilities" / "BooleanCapability.cs",
    "N": ROOT / "src" / "Capabilities" / "NumericCapability.cs",
    "S": ROOT / "src" / "Capabilities" / "StringCapability.cs",
}


@dataclass(frozen=True)
class Capability:
    kind: str
    binary_index: int
    short_name: str
    long_name: str
    termcap_code: str
    managed_name: str


def parse_source() -> list[Capability]:
    lines = SOURCE.read_text(encoding="utf-8").splitlines()
    data_lines = [line for line in lines if line and not line.startswith("#")]
    if not data_lines:
        raise ValueError("The canonical capability table is empty.")

    expected_header = (
        "Kind\tBinaryIndex\tShortName\tLongName\tTermcapCode\tManagedName"
    )
    if data_lines[0] != expected_header:
        raise ValueError("Unexpected canonical capability table header.")

    capabilities: list[Capability] = []
    for line_number, line in enumerate(data_lines[1:], start=2):
        fields = line.split("\t")
        if len(fields) != 6:
            raise ValueError(
                f"Canonical row {line_number} has {len(fields)} fields; expected 6."
            )

        kind, index_text, short_name, long_name, termcap_code, managed_name = fields
        if kind not in KIND_INFO:
            raise ValueError(f"Unknown capability kind {kind!r} on row {line_number}.")

        capabilities.append(
            Capability(
                kind=kind,
                binary_index=int(index_text),
                short_name=short_name,
                long_name=long_name,
                termcap_code=termcap_code,
                managed_name=managed_name,
            )
        )

    validate(capabilities)
    return capabilities


def validate(capabilities: list[Capability]) -> None:
    for kind, expected_count in EXPECTED_COUNTS.items():
        items = [item for item in capabilities if item.kind == kind]
        if len(items) != expected_count:
            raise ValueError(
                f"Capability kind {kind} has {len(items)} rows; expected {expected_count}."
            )

        actual_indices = [item.binary_index for item in items]
        expected_indices = list(range(expected_count))
        if actual_indices != expected_indices:
            raise ValueError(
                f"Capability kind {kind} does not have contiguous binary indices."
            )

        assert_unique(items, "short_name", kind)
        assert_unique(items, "long_name", kind)
        assert_unique(items, "managed_name", kind)
        validate_enum_names(kind, items)


def assert_unique(
    items: list[Capability],
    attribute: str,
    kind: str,
) -> None:
    values = [getattr(item, attribute) for item in items]
    if len(values) != len(set(values)):
        raise ValueError(
            f"Capability kind {kind} contains duplicate {attribute} values."
        )


def validate_enum_names(kind: str, items: list[Capability]) -> None:
    source = ENUM_FILES[kind].read_text(encoding="utf-8")
    enum_names = set(
        re.findall(r"^\s{4}([A-Za-z_][A-Za-z0-9_]*)\s*(?:=\s*[^,]+)?,$", source, re.MULTILINE)
    )
    expected_names = {item.managed_name for item in items}

    missing = sorted(expected_names - enum_names)
    extra = sorted(enum_names - expected_names)
    if missing or extra:
        details = []
        if missing:
            details.append("missing enum members: " + ", ".join(missing))
        if extra:
            details.append("unmapped enum members: " + ", ".join(extra))
        raise ValueError("; ".join(details))


def generate(capabilities: list[Capability]) -> str:
    lines = [
        "// <auto-generated>",
        "// Generated from tools/terminfo-metadata/standard-capabilities.tsv.",
        "// Do not edit by hand; run tools/terminfo-metadata/generate.py.",
        "// </auto-generated>",
        "",
        "namespace Icod.TermInfo;",
        "",
        "internal static class StandardCapabilityDefinitions",
        "{",
    ]

    for kind in ("B", "N", "S"):
        label, enum_type, value_kind = KIND_INFO[kind]
        items = [item for item in capabilities if item.kind == kind]
        lines.extend(
            [
                f"    internal static readonly StandardCapabilityMetadata<{enum_type}>[] {label} =",
                "    [",
            ]
        )
        for item in items:
            lines.append(
                "        new("
                f"{enum_type}.{item.managed_name}, "
                f"{item.binary_index}, "
                f'"{escape(item.short_name)}", '
                f'"{escape(item.long_name)}", '
                f'"{escape(item.termcap_code)}", '
                f"TermInfoCapabilityValueKind.{value_kind}),"
            )
        lines.extend(["    ];", ""])

    lines.append("}")
    return "\n".join(lines) + "\n"


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the checked-in generated file is current",
    )
    args = parser.parse_args()

    generated = generate(parse_source())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"{OUTPUT.relative_to(ROOT)} is not current; regenerate it.",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
