from pathlib import Path


def replace_exact(path_name: str, old: str, new: str) -> None:
    path = Path(path_name)
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path_name}: expected one match, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8", newline="\n")


replace_exact(
    "Icod.TermInfo.Inspection/src/TermInfoDatabaseSet.SemanticAnalysis.cs",
    '''\t\tDictionary<string, List<TermInfoDatabaseSetOccurrence>> aliasOccurrences =\n\t\t\tnew( StringComparer.Ordinal );\n\t\tint aliasOccurrenceCount = 0;\n\t\tforeach ( TermInfoDatabaseSetIdentity identity in Identities ) {\n\t\t\tforeach ( TermInfoDatabaseSetOccurrence occurrence in identity.Occurrences ) {\n\t\t\t\tcancellationToken.ThrowIfCancellationRequested();\n\t\t\t\tforeach ( string alias in occurrence.Aliases ) {\n\t\t\t\t\tcancellationToken.ThrowIfCancellationRequested();\n\t\t\t\t\taliasOccurrenceCount = checked( aliasOccurrenceCount + 1 );\n\t\t\t\t\tif ( aliasOccurrenceCount > effectiveOptions.MaximumAliasOccurrenceCount ) {\n\t\t\t\t\t\tthrow new InvalidOperationException(\n\t\t\t\t\t\t\t$"Database-set semantic analysis exceeds the configured maximum of {effectiveOptions.MaximumAliasOccurrenceCount} alias occurrences."\n\t\t\t\t\t\t);\n\t\t\t\t\t}\n\n\t\t\t\t\tif ( !aliasOccurrences.TryGetValue(\n\t\t\t\t\t\talias,\n\t\t\t\t\t\tout List<TermInfoDatabaseSetOccurrence>? occurrences\n\t\t\t\t\t) ) {\n\t\t\t\t\t\toccurrences = [];\n\t\t\t\t\t\taliasOccurrences.Add( alias, occurrences );\n\t\t\t\t\t}\n\t\t\t\t\toccurrences.Add( occurrence );\n\t\t\t\t}\n\t\t\t}\n\t\t}\n''',
    '''\t\tDictionary<string, List<TermInfoDatabaseSetOccurrence>> aliasOccurrences =\n\t\t\tnew( StringComparer.Ordinal );\n\t\tint aliasOccurrenceCount = 0;\n\t\tIEnumerable<TermInfoDatabaseSetOccurrence> orderedOccurrences =\n\t\t\tIdentities\n\t\t\t\t.SelectMany( identity => identity.Occurrences )\n\t\t\t\t.OrderBy( occurrence => occurrence.DatabaseIndex )\n\t\t\t\t.ThenBy( occurrence => occurrence.CatalogEntryIndex );\n\t\tforeach ( TermInfoDatabaseSetOccurrence occurrence in orderedOccurrences ) {\n\t\t\tcancellationToken.ThrowIfCancellationRequested();\n\t\t\tforeach ( string alias in occurrence.Aliases ) {\n\t\t\t\tcancellationToken.ThrowIfCancellationRequested();\n\t\t\t\taliasOccurrenceCount = checked( aliasOccurrenceCount + 1 );\n\t\t\t\tif ( aliasOccurrenceCount > effectiveOptions.MaximumAliasOccurrenceCount ) {\n\t\t\t\t\tthrow new InvalidOperationException(\n\t\t\t\t\t\t$"Database-set semantic analysis exceeds the configured maximum of {effectiveOptions.MaximumAliasOccurrenceCount} alias occurrences."\n\t\t\t\t\t);\n\t\t\t\t}\n\n\t\t\t\tif ( !aliasOccurrences.TryGetValue(\n\t\t\t\t\talias,\n\t\t\t\t\tout List<TermInfoDatabaseSetOccurrence>? occurrences\n\t\t\t\t) ) {\n\t\t\t\t\toccurrences = [];\n\t\t\t\t\taliasOccurrences.Add( alias, occurrences );\n\t\t\t\t}\n\t\t\t\toccurrences.Add( occurrence );\n\t\t\t}\n\t\t}\n''',
)

replace_exact(
    "tests/Icod.TermInfo.Inspection.Tests/src/DA03SemanticDuplicateAliasShadowTests.cs",
    '''\t[Fact]\n\tpublic void SameAliasOwnedByDifferentCanonicalNamesIsExplicitConflict() {\n\t\tTermInfoDatabaseSet set =\n\t\t\tTermInfoDatabaseInspector.CreateSet(\n\t\t\t\t[\n\t\t\t\t\tCreateCatalog(\n\t\t\t\t\t\t"owner-a",\n\t\t\t\t\t\tCreateTerminal( "alpha", 80, "shared" )\n\t\t\t\t\t),\n\t\t\t\t\tCreateCatalog(\n\t\t\t\t\t\t"owner-b",\n\t\t\t\t\t\tCreateTerminal( "beta", 80, "shared" )\n\t\t\t\t\t),\n\t\t\t\t]\n\t\t\t);\n\n\t\tTermInfoDatabaseSetAliasAnalysis alias =\n\t\t\tAssert.Single(\n\t\t\t\tset.AnalyzeSemantics(\n\t\t\t\t\tcancellationToken: CancellationToken.None\n\t\t\t\t).Aliases\n\t\t\t);\n\n\t\tAssert.Equal(\n\t\t\tTermInfoDatabaseSetSemanticRelationship.SemanticallyDifferent,\n\t\t\talias.Relationship\n\t\t);\n\t\tAssert.Equal( new[] { "alpha", "beta" }, alias.CanonicalNames );\n\t\tAssert.True( alias.HasMultipleCanonicalOwners );\n\t}\n''',
    '''\t[Fact]\n\tpublic void SameAliasOwnedByDifferentCanonicalNamesIsExplicitConflict() {\n\t\tTermInfoDatabaseSet set =\n\t\t\tTermInfoDatabaseInspector.CreateSet(\n\t\t\t\t[\n\t\t\t\t\tCreateCatalog(\n\t\t\t\t\t\t"owner-first",\n\t\t\t\t\t\tCreateTerminal( "zeta", 80, "shared" )\n\t\t\t\t\t),\n\t\t\t\t\tCreateCatalog(\n\t\t\t\t\t\t"owner-second",\n\t\t\t\t\t\tCreateTerminal( "alpha", 80, "shared" )\n\t\t\t\t\t),\n\t\t\t\t]\n\t\t\t);\n\n\t\tTermInfoDatabaseSetAliasAnalysis alias =\n\t\t\tAssert.Single(\n\t\t\t\tset.AnalyzeSemantics(\n\t\t\t\t\tcancellationToken: CancellationToken.None\n\t\t\t\t).Aliases\n\t\t\t);\n\t\tTermInfoDatabaseSetOccurrence owner =\n\t\t\tAssert.IsType<TermInfoDatabaseSetOccurrence>( alias.PrecedenceOwner );\n\n\t\tAssert.Equal(\n\t\t\tTermInfoDatabaseSetSemanticRelationship.SemanticallyDifferent,\n\t\t\talias.Relationship\n\t\t);\n\t\tAssert.Equal( new[] { "alpha", "zeta" }, alias.CanonicalNames );\n\t\tAssert.Equal( new[] { 0, 1 }, alias.Occurrences.Select( occurrence => occurrence.DatabaseIndex ).ToArray() );\n\t\tAssert.Equal( "zeta", owner.Name );\n\t\tAssert.Equal( 0, owner.DatabaseIndex );\n\t\tAssert.True( alias.HasMultipleCanonicalOwners );\n\t}\n''',
)

replace_exact(
    "docs/1.10.0-DA03-SEMANTIC-DUPLICATE-CONFLICT-ALIAS-AND-SHADOW-ANALYSIS.md",
    "Each alias analysis retains ordered physical declarations, distinct canonical\nowner names, the first declared precedence owner when earlier incomplete roots do\nnot block it, an exact canonical-name collision when present, completeness, and\nblocking database indices.",
    "Each alias analysis retains physical declarations in database and catalog-entry\norder, distinct canonical owner names in ordinal order, the first declared\nprecedence owner when earlier incomplete roots do not block it, an exact\ncanonical-name collision when present, completeness, and blocking database\nindices. Alias declaration order never depends on canonical identity sorting.",
)
