<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>Icod.TermInfo.FixtureGenerator</AssemblyName>
    <RootNamespace>Icod.TermInfo.FixtureGenerator</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
