<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>Icod.TermInfo.Sample</AssemblyName>
    <RootNamespace>Icod.TermInfo.Sample</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Icod.TermInfo.csproj" />
  </ItemGroup>
</Project>
