<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Icod.TermInfo.PackageVerifier</AssemblyName>
    <RootNamespace>Icod.TermInfo.PackageVerifier</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
